name: Lint/Test Conda
on: [push, pull_request]

jobs:
  test:
    name: (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "windows-latest"]
        python-version: ["3.10"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Conda info
        shell: bash -l {0}
        run: conda info

      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install pip
          pip install --upgrade setuptools
          pip install -r requirements.txt
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          cd tests
          pytest test_pmClient.py 